### Task 1
- Import Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
test_dataset = pd.read_csv('test.csv')
train_dataset = pd.read_csv('train.csv')
test_dataset.shape, train_dataset.shape

((11709, 80), (27321, 80))

In [3]:
test_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11709 entries, 0 to 11708
Data columns (total 80 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   UID                          11709 non-null  int64
 1   BLOCKID                      0 non-null      float64
 2   SUMLEVEL                     11709 non-null  int64
 3   COUNTYID                     11709 non-null  int64
 4   STATEID                      11709 non-null  int64
 5   state                        11709 non-null  object
 6   state_ab                     11709 non-null  object
 7   city                         11709 non-null  object
 8   place                        11709 non-null  object
 9   type                         11709 non-null  object
 10  primary                      11709 non-null  object
 11  zip_code                     11709 non-null  int64
 12  area_code                    11709 non-null  int64
 13  lat                          11709 non-null  float64
 14  lng                          11709 non-null  float64
 15  ALand                        11709 non-null  int64
 16  AWater                       11709 non-null  int64
 17  pop                          11709 non-null  int64
 18  male_pop                     11709 non-null  int64
 19  female_pop                   11709 non-null  int64
 20  rent_mean                    11561 non-null  float64
 21  rent_median                  11561 non-null  float64
 22  rent_stdev                   11561 non-null  float64
 23  rent_sample_weight           11561 non-null  float64
 24  rent_samples                 11561 non-null  float64
 25  rent_gt_10                   11560 non-null  float64
 26  rent_gt_15                   11560 non-null  float64
 27  rent_gt_20                   11560 non-null  float64
 28  rent_gt_25                   11560 non-null  float64
 29  rent_gt_30                   11560 non-null  float64
 30  rent_gt_35                   11560 non-null  float64
 31  rent_gt_40                   11560 non-null  float64
 32  rent_gt_50                   11560 non-null  float64
 33  universe_samples             11709 non-null  int64
 34  used_samples                 11709 non-null  int64
 35  hi_mean                      11587 non-null  float64
 36  hi_median                    11587 non-null  float64
 37  hi_stdev                     11587 non-null  float64
 38  hi_sample_weight             11587 non-null  float64
 39  hi_samples                   11587 non-null  float64
 40  family_mean                  11573 non-null  float64
 41  family_median                11573 non-null  float64
 42  family_stdev                 11573 non-null  float64
 43  family_sample_weight         11573 non-null  float64
 44  family_samples               11573 non-null  float64
 45  hc_mortgage_mean             11441 non-null  float64
 46  hc_mortgage_median           11441 non-null  float64
 47  hc_mortgage_stdev            11441 non-null  float64
 48  hc_mortgage_sample_weight    11441 non-null  float64
 49  hc_mortgage_samples          11441 non-null  float64
 50  hc_mean                      11419 non-null  float64
 51  hc_median                    11419 non-null  float64
 52  hc_stdev                     11419 non-null  float64
 53  hc_samples                   11419 non-null  float64
 54  hc_sample_weight             11419 non-null  float64
 55  home_equity_second_mortgage  11489 non-null  float64
 56  second_mortgage              11489 non-null  float64
 57  home_equity                  11489 non-null  float64
 58  debt                         11489 non-null  float64
 59  second_mortgage_cdf          11489 non-null  float64
 60  home_equity_cdf              11489 non-null  float64
 61  debt_cdf                     11489 non-null  float64
 62  hs_degree                    11624 non-null  float64
 63  hs_degree_male               11620 non-null  float64
 64  hs_degree_female             11604 non-null  float64
 65  male_age_mean                11625 non-null  float64
 66  male_age_median              11625 non-null  float64
 67  male_age_stdev               11625 non-null  float64
 68  male_age_sample_weight       11625 non-null  float64
 69  male_age_samples             11625 non-null  float64
 70  female_age_mean              11613 non-null  float64
 71  female_age_median            11613 non-null  float64
 72  female_age_stdev             11613 non-null  float64
 73  female_age_sample_weight     11613 non-null  float64
 74  female_age_samples           11613 non-null  float64
 75  pct_own                      11587 non-null  float64
 76  married                      11625 non-null  float64
 77  married_snp                  11625 non-null  float64
 78  separated                    11625 non-null  float64
 79  divorced                     11625 non-null  float64
dtypes: float64(61), int64(13), object(6)
memory usage: 7.1+ MB

In [4]:
train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27321 entries, 0 to 27320
Data columns (total 80 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   UID                          27321 non-null  int64
 1   BLOCKID                      0 non-null      float64
 2   SUMLEVEL                     27321 non-null  int64
 3   COUNTYID                     27321 non-null  int64
 4   STATEID                      27321 non-null  int64
 5   state                        27321 non-null  object
 6   state_ab                     27321 non-null  object
 7   city                         27321 non-null  object
 8   place                        27321 non-null  object
 9   type                         27321 non-null  object
 10  primary                      27321 non-null  object
 11  zip_code                     27321 non-null  int64
 12  area_code                    27321 non-null  int64
 13  lat                          27321 non-null  float64
 14  lng                          27321 non-null  float64
 15  ALand                        27321 non-null  float64
 16  AWater                       27321 non-null  int64
 17  pop                          27321 non-null  int64
 18  male_pop                     27321 non-null  int64
 19  female_pop                   27321 non-null  int64
 20  rent_mean                    27007 non-null  float64
 21  rent_median                  27007 non-null  float64
 22  rent_stdev                   27007 non-null  float64
 23  rent_sample_weight           27007 non-null  float64
 24  rent_samples                 27007 non-null  float64
 25  rent_gt_10                   27007 non-null  float64
 26  rent_gt_15                   27007 non-null  float64
 27  rent_gt_20                   27007 non-null  float64
 28  rent_gt_25                   27007 non-null  float64
 29  rent_gt_30                   27007 non-null  float64
 30  rent_gt_35                   27007 non-null  float64
 31  rent_gt_40                   27007 non-null  float64
 32  rent_gt_50                   27007 non-null  float64
 33  universe_samples             27321 non-null  int64
 34  used_samples                 27321 non-null  int64
 35  hi_mean                      27053 non-null  float64
 36  hi_median                    27053 non-null  float64
 37  hi_stdev                     27053 non-null  float64
 38  hi_sample_weight             27053 non-null  float64
 39  hi_samples                   27053 non-null  float64
 40  family_mean                  27023 non-null  float64
 41  family_median                27023 non-null  float64
 42  family_stdev                 27023 non-null  float64
 43  family_sample_weight         27023 non-null  float64
 44  family_samples               27023 non-null  float64
 45  hc_mortgage_mean             26748 non-null  float64
 46  hc_mortgage_median           26748 non-null  float64
 47  hc_mortgage_stdev            26748 non-null  float64
 48  hc_mortgage_sample_weight    26748 non-null  float64
 49  hc_mortgage_samples          26748 non-null  float64
 50  hc_mean                      26721 non-null  float64
 51  hc_median                    26721 non-null  float64
 52  hc_stdev                     26721 non-null  float64
 53  hc_samples                   26721 non-null  float64
 54  hc_sample_weight             26721 non-null  float64
 55  home_equity_second_mortgage  26864 non-null  float64
 56  second_mortgage              26864 non-null  float64
 57  home_equity                  26864 non-null  float64
 58  debt                         26864 non-null  float64
 59  second_mortgage_cdf          26864 non-null  float64
 60  home_equity_cdf              26864 non-null  float64
 61  debt_cdf                     26864 non-null  float64
 62  hs_degree                    27131 non-null  float64
 63  hs_degree_male               27121 non-null  float64
 64  hs_degree_female             27098 non-null  float64
 65  male_age_mean                27132 non-null  float64
 66  male_age_median              27132 non-null  float64
 67  male_age_stdev               27132 non-null  float64
 68  male_age_sample_weight       27132 non-null  float64
 69  male_age_samples             27132 non-null  float64
 70  female_age_mean              27115 non-null  float64
 71  female_age_median            27115 non-null  float64
 72  female_age_stdev             27115 non-null  float64
 73  female_age_sample_weight     27115 non-null  float64
 74  female_age_samples           27115 non-null  float64
 75  pct_own                      27053 non-null  float64
 76  married                      27130 non-null  float64
 77  married_snp                  27130 non-null  float64
 78  separated                    27130 non-null  float64
 79  divorced                     27130 non-null  float64
dtypes: float64(62), int64(12), object(6)
memory usage: 16.7+ MB

train_dataset.to_excel('train_data.xlsx')
test_dataset.to_excel('test_data.xlsx')

### Task 2
- Figure out primary key and look for requirement of indexing.

In [5]:
test_dataset['UID'].nunique()

11677

In [6]:
# count of unique values in each feature
for i in test_dataset.columns:
    print('unique value counts for {}: {}'.format(i, test_dataset[i].nunique()))

unique value counts for UID: 11677
unique value counts for BLOCKID: 0
unique value counts for SUMLEVEL: 1
unique value counts for COUNTYID: 246
unique value counts for STATEID: 52
unique value counts for state: 52
unique value counts for state_ab: 52
unique value counts for city: 4369
unique value counts for place: 5902
unique value counts for type: 6
unique value counts for primary: 1
unique value counts for zip_code: 7788
unique value counts for area_code: 268
unique value counts for lat: 11676
unique value counts for lng: 11677
unique value counts for ALand: 11677
unique value counts for AWater: 7026
unique value counts for pop: 5692
unique value counts for male_pop: 3663
unique value counts for female_pop: 3770
unique value counts for rent_mean: 11499
unique value counts for rent_median: 1930
unique value counts for rent_stdev: 11494
unique value counts for rent_sample_weight: 11495
unique value counts for rent_samples: 1838
unique value counts for rent_gt_10: 5038
unique value counts for rent_gt_15: 7715
unique value counts for rent_gt_20: 8756
unique value counts for rent_gt_25: 9156
unique value counts for rent_gt_30: 9200
unique value counts for rent_gt_35: 9212
unique value counts for rent_gt_40: 9105
unique value counts for rent_gt_50: 8749
unique value counts for universe_samples: 1857
unique value counts for used_samples: 1805
unique value counts for hi_mean: 11559
unique value counts for hi_median: 10768
unique value counts for hi_stdev: 11556
unique value counts for hi_sample_weight: 11562
unique value counts for hi_samples: 2935
unique value counts for family_mean: 11550
unique value counts for family_median: 10883
unique value counts for family_stdev: 11548
unique value counts for family_sample_weight: 11550
unique value counts for family_samples: 2314
unique value counts for hc_mortgage_mean: 11376
unique value counts for hc_mortgage_median: 2564
unique value counts for hc_mortgage_stdev: 11370
unique value counts for hc_mortgage_sample_weight: 11387
unique value counts for hc_mortgage_samples: 1881
unique value counts for hc_mean: 11323
unique value counts for hc_median: 1214
unique value counts for hc_stdev: 11318
unique value counts for hc_samples: 1141
unique value counts for hc_sample_weight: 10851
unique value counts for home_equity_second_mortgage: 4914
unique value counts for second_mortgage: 5348
unique value counts for home_equity: 8236
unique value counts for debt: 9944
unique value counts for second_mortgage_cdf: 7397
unique value counts for home_equity_cdf: 9166
unique value counts for debt_cdf: 10158
unique value counts for hs_degree: 9666
unique value counts for hs_degree_male: 9536
unique value counts for hs_degree_female: 9356
unique value counts for male_age_mean: 11570
unique value counts for male_age_median: 596
unique value counts for male_age_stdev: 11505
unique value counts for male_age_sample_weight: 11600
unique value counts for male_age_samples: 3662
unique value counts for female_age_mean: 11552
unique value counts for female_age_median: 595
unique value counts for female_age_stdev: 11472
unique value counts for female_age_sample_weight: 11587
unique value counts for female_age_samples: 3769
unique value counts for pct_own: 10578
unique value counts for married: 10215
unique value counts for married_snp: 6829
unique value counts for separated: 4512
unique value counts for divorced: 8273

### Task 3
- Missing value treatment
    - Explain reason chosen for each variable

In [7]:
# missing/null values in each feature of test
missing_values = []
missing_values_overall_count = test_dataset.isnull().sum()
for i in test_dataset.columns:
    if test_dataset[i].isnull().sum() > 1:
        missing_values.append(i)
        print('missing values for {}: {}'.format(i, test_dataset[i].isnull().sum()))
print('number of columns with missing values:',len(missing_values))

missing values for BLOCKID: 11709
missing values for rent_mean: 148
missing values for rent_median: 148
missing values for rent_stdev: 148
missing values for rent_sample_weight: 148
missing values for rent_samples: 148
missing values for rent_gt_10: 149
missing values for rent_gt_15: 149
missing values for rent_gt_20: 149
missing values for rent_gt_25: 149
missing values for rent_gt_30: 149
missing values for rent_gt_35: 149
missing values for rent_gt_40: 149
missing values for rent_gt_50: 149
missing values for hi_mean: 122
missing values for hi_median: 122
missing values for hi_stdev: 122
missing values for hi_sample_weight: 122
missing values for hi_samples: 122
missing values for family_mean: 136
missing values for family_median: 136
missing values for family_stdev: 136
missing values for family_sample_weight: 136
missing values for family_samples: 136
missing values for hc_mortgage_mean: 268
missing values for hc_mortgage_median: 268
missing values for hc_mortgage_stdev: 268
missing values for hc_mortgage_sample_weight: 268
missing values for hc_mortgage_samples: 268
missing values for hc_mean: 290
missing values for hc_median: 290
missing values for hc_stdev: 290
missing values for hc_samples: 290
missing values for hc_sample_weight: 290
missing values for home_equity_second_mortgage: 220
missing values for second_mortgage: 220
missing values for home_equity: 220
missing values for debt: 220
missing values for second_mortgage_cdf: 220
missing values for home_equity_cdf: 220
missing values for debt_cdf: 220
missing values for hs_degree: 85
missing values for hs_degree_male: 89
missing values for hs_degree_female: 105
missing values for male_age_mean: 84
missing values for male_age_median: 84
missing values for male_age_stdev: 84
missing values for male_age_sample_weight: 84
missing values for male_age_samples: 84
missing values for female_age_mean: 96
missing values for female_age_median: 96
missing values for female_age_stdev: 96
missing values for female_age_sample_weight: 96
missing values for female_age_samples: 96
missing values for pct_own: 122
missing values for married: 84
missing values for married_snp: 84
missing values for separated: 84
missing values for divorced: 84
number of columns with missing values: 59

In [8]:
# dropping BLOCKID; There are no values
test_dataset.shape,train_dataset.shape
test_dataset.drop(columns='BLOCKID', inplace=True)
train_dataset.drop(columns='BLOCKID', inplace=True)
test_dataset.shape,train_dataset.shape

((11709, 79), (27321, 79))

In [9]:
# drop records where used_samples=0; These samples are missing data that will provide value during computation.
used_samples_0 = test_dataset.loc[test_dataset['used_samples'] == 0].index
print('test_data shape before dropping used_samples = 0 records:{}'.format(test_dataset.shape))
test_dataset.drop(index=used_samples_0, inplace=True)
print('test_data shape after dropping used_samples = 0 records:{}'.format(test_dataset.shape))

test_data shape before dropping used_samples = 0 records:(11709, 79)
test_data shape after dropping used_samples = 0 records:(11560, 79)

In [10]:
missing_values = []
for i in test_dataset.columns:
    if test_dataset[i].isnull().sum() > 1:
        missing_values.append(i)
        print('missing values for {}: {}'.format(i, test_dataset[i].isnull().sum()))
print('number of columns with missing values:',len(missing_values))

missing values for family_mean: 7
missing values for family_median: 7
missing values for family_stdev: 7
missing values for family_sample_weight: 7
missing values for family_samples: 7
missing values for hc_mortgage_mean: 142
missing values for hc_mortgage_median: 142
missing values for hc_mortgage_stdev: 142
missing values for hc_mortgage_sample_weight: 142
missing values for hc_mortgage_samples: 142
missing values for hc_mean: 160
missing values for hc_median: 160
missing values for hc_stdev: 160
missing values for hc_samples: 160
missing values for hc_sample_weight: 160
missing values for home_equity_second_mortgage: 97
missing values for second_mortgage: 97
missing values for home_equity: 97
missing values for debt: 97
missing values for second_mortgage_cdf: 97
missing values for home_equity_cdf: 97
missing values for debt_cdf: 97
missing values for hs_degree: 2
missing values for hs_degree_male: 4
missing values for hs_degree_female: 6
missing values for male_age_mean: 2
missing values for male_age_median: 2
missing values for male_age_stdev: 2
missing values for male_age_sample_weight: 2
missing values for male_age_samples: 2
missing values for female_age_mean: 2
missing values for female_age_median: 2
missing values for female_age_stdev: 2
missing values for female_age_sample_weight: 2
missing values for female_age_samples: 2
missing values for married: 2
missing values for married_snp: 2
missing values for separated: 2
missing values for divorced: 2
number of columns with missing values: 39

In [11]:
test_dataset.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11560 entries, 0 to 11708
Data columns (total 79 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   UID                          11560 non-null  int64
 1   SUMLEVEL                     11560 non-null  int64
 2   COUNTYID                     11560 non-null  int64
 3   STATEID                      11560 non-null  int64
 4   state                        11560 non-null  object
 5   state_ab                     11560 non-null  object
 6   city                         11560 non-null  object
 7   place                        11560 non-null  object
 8   type                         11560 non-null  object
 9   primary                      11560 non-null  object
 10  zip_code                     11560 non-null  int64
 11  area_code                    11560 non-null  int64
 12  lat                          11560 non-null  float64
 13  lng                          11560 non-null  float64
 14  ALand                        11560 non-null  int64
 15  AWater                       11560 non-null  int64
 16  pop                          11560 non-null  int64
 17  male_pop                     11560 non-null  int64
 18  female_pop                   11560 non-null  int64
 19  rent_mean                    11560 non-null  float64
 20  rent_median                  11560 non-null  float64
 21  rent_stdev                   11560 non-null  float64
 22  rent_sample_weight           11560 non-null  float64
 23  rent_samples                 11560 non-null  float64
 24  rent_gt_10                   11560 non-null  float64
 25  rent_gt_15                   11560 non-null  float64
 26  rent_gt_20                   11560 non-null  float64
 27  rent_gt_25                   11560 non-null  float64
 28  rent_gt_30                   11560 non-null  float64
 29  rent_gt_35                   11560 non-null  float64
 30  rent_gt_40                   11560 non-null  float64
 31  rent_gt_50                   11560 non-null  float64
 32  universe_samples             11560 non-null  int64
 33  used_samples                 11560 non-null  int64
 34  hi_mean                      11560 non-null  float64
 35  hi_median                    11560 non-null  float64
 36  hi_stdev                     11560 non-null  float64
 37  hi_sample_weight             11560 non-null  float64
 38  hi_samples                   11560 non-null  float64
 39  family_mean                  11553 non-null  float64
 40  family_median                11553 non-null  float64
 41  family_stdev                 11553 non-null  float64
 42  family_sample_weight         11553 non-null  float64
 43  family_samples               11553 non-null  float64
 44  hc_mortgage_mean             11418 non-null  float64
 45  hc_mortgage_median           11418 non-null  float64
 46  hc_mortgage_stdev            11418 non-null  float64
 47  hc_mortgage_sample_weight    11418 non-null  float64
 48  hc_mortgage_samples          11418 non-null  float64
 49  hc_mean                      11400 non-null  float64
 50  hc_median                    11400 non-null  float64
 51  hc_stdev                     11400 non-null  float64
 52  hc_samples                   11400 non-null  float64
 53  hc_sample_weight             11400 non-null  float64
 54  home_equity_second_mortgage  11463 non-null  float64
 55  second_mortgage              11463 non-null  float64
 56  home_equity                  11463 non-null  float64
 57  debt                         11463 non-null  float64
 58  second_mortgage_cdf          11463 non-null  float64
 59  home_equity_cdf              11463 non-null  float64
 60  debt_cdf                     11463 non-null  float64
 61  hs_degree                    11558 non-null  float64
 62  hs_degree_male               11556 non-null  float64
 63  hs_degree_female             11554 non-null  float64
 64  male_age_mean                11558 non-null  float64
 65  male_age_median              11558 non-null  float64
 66  male_age_stdev               11558 non-null  float64
 67  male_age_sample_weight       11558 non-null  float64
 68  male_age_samples             11558 non-null  float64
 69  female_age_mean              11558 non-null  float64
 70  female_age_median            11558 non-null  float64
 71  female_age_stdev             11558 non-null  float64
 72  female_age_sample_weight     11558 non-null  float64
 73  female_age_samples           11558 non-null  float64
 74  pct_own                      11560 non-null  float64
 75  married                      11558 non-null  float64
 76  married_snp                  11558 non-null  float64
 77  separated                    11558 non-null  float64
 78  divorced                     11558 non-null  float64
dtypes: float64(60), int64(13), object(6)
memory usage: 7.1+ MB